### ISSUE TITLE
IMG_2719.JPG  annotations are corrupted

### ISSUE THREAD

**Issue by AsherYartsevTech** [AsherYartsevTech/Mask_RCNN#7]
during training when trying to load it next exception appears:
`
Traceback (most recent call last):
  File "/home/simon/Mask_RCNN/mrcnn/model.py", line 1722, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/simon/Mask_RCNN/mrcnn/model.py", line 1223, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "cucuTrain.py", line 519, in load_mask
    image_info["width"])
  File "cucuTrain.py", line 570, in annToMask
    rle = self.annToRLE(ann, height, width)
  File "cucuTrain.py", line 555, in annToRLE
    rles = maskUtils.frPyObjects(segm, height, width)
  File "pycocotools/_mask.pyx", line 293, in pycocotools._mask.frPyObjects
TypeError: Argument 'bb' has incorrect type (expected numpy.ndarray, got list)
`

**Comment by simonlousky** [comment]
If this is what I think, I should have told you this could happen. 
I think this picture exists in another directory of the dataset.
